name: Free Linux Shell via GitHub Actions

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ "main" ]

jobs:
  linux-shell:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: System info and basic setup
        run: |
          echo "=== System Information ==="
          uname -a
          lsb_release -a
          df -h
          free -h
          nproc
          
          echo "=== Installing useful tools ==="
          sudo apt-get update
          sudo apt-get install -y htop neofetch tmux vim git curl wget
          
      - name: Create workspace directory
        run: |
          mkdir -p ~/workspace
          cd ~/workspace
          echo "Working directory: $(pwd)"
          
      - name: Your custom commands here
        run: |
          # Add your commands here
          echo "Ready for work!"
          neofetch
          
      # Debug shell - requires SSH key on your GitHub profile
      - name: Setup interactive SSH session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
          wait-timeout-minutes: 30
        if: ${{ github.event_name == 'workflow_dispatch' }}
